title: Mateus Medeiros - Desenvolvedor Front End
email: mateus.sousamedeiros@gmail.com
description: "Site do Desenvolvedor Front-End Mateus Medeiros. HTML5, CSS3, JavaScript, jQuery, Sass, Gulp, WordPress, Freelancer"
url: "https://mateusmedeiros.com/"
twitter_username: mateussousam
github_username:  mateussmedeiros

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: "/blog/:num"
pages_to_cache:
 - /offline/index.html
 
sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-paginate