title: Mateus Medeiros - Desenvolvedor Front End
email: mateus.sousamedeiros@gmail.com
description: "Site do Desenvolvedor Front End Mateus Medeiros. HTML5, CSS3, JavaScript, jQuery, Sass, Gulp, WordPress, Freelancer"
url: "https://mateusmedeiros.com/"
twitter_username: mateussousam
github_username:  mateussmedeiros

# Build settings
markdown: kramdown
permalink: /:title/
#paginate: 5
#paginate_path: "/blog/page/:num"

#plugins:
  #- jekyll-sitemap
  #- jekyll-paginate