title: Mateus Medeiros - Desenvolvedor Front End
email: mateus.sousamedeiros@gmail.com
description: "Blog de um Desenvolvedor Front End apaixonado por novas tecnologias, abordando assuntos sobre Desenvolvimento Web, com foco em Front End"
url: "http://mateussmedeiros.github.io/" 
twitter_username: mateussousam
github_username:  mateussmedeiros

# Build settings
markdown: kramdown
permalink: /:title/

gems:
  - jekyll-sitemap

css_folder:  "/assets/css"
js_folder:  "/assets/js"
img_folder:  "/assets/img"
sass:
    style: compressed